var links = [
{'caption':'Dissektion af ørred',
'link':'https://www.dropbox.com/s/03ly80jow612q7r/Dissektion%20af%20%C3%B8rred.pdf?dl=0'},
{'caption':'Fotosyntese hos karse',
'link':'https://www.dropbox.com/s/edssu6owrvisd8g/Fotosyntese%20hos%20karse.pdf?dl=0'},
{'caption':'Fotosyntese og respiration',
'link':'https://www.dropbox.com/s/mynyaicigpw2axv/Fotosyntese%20og%20respiration.pdf?dl=0'},
{'caption':'Primærproduktion hos enårige planter',
'link':'https://www.dropbox.com/s/7kdonfpayf1o5jb/Prim%C3%A6rproduktion%20hos%20en%C3%A5rige%20planter.pdf?dl=0'},
{'caption':'Respiration og fotosyntese hos vandpest',
'link':'https://www.dropbox.com/s/vkryfqjb839f5r5/Respiration%20og%20fotosyntese%20hos%20vandpest.pdf?dl=0'},
{'caption':'Spalteåbninger hos planter',
'link':'https://www.dropbox.com/s/5dn52zq7mhfmreu/Spalte%C3%A5bninger%20hos%20planter.pdf?dl=0'},
{'caption':'Springlag',
'link':'https://www.dropbox.com/s/5c3mpx38j7b1hu0/Springlag.pdf?dl=0'},
{'caption':'Vanddyrs tilpasninger',
'link':'https://www.dropbox.com/s/ig4wtsyt9ho6brx/Vanddyrs%20tilpasninger.pdf?dl=0'},
{'caption':'Øko-race',
'link':'https://www.dropbox.com/s/pngh7rmar03sj20/%C3%98ko-race.pdf?dl=0'},
]
