var schools = {
"Gymnasier": [
"Aalborg City Gymnasium",
"Aalborg Katedralskole",
"Aalborghus Gymnasium",
"Aarhus Handelsgymnasium",
"Aarhus HF & VUC",
"Aarhus Statsgymnasium",
"Akademisk Studenterkursus",
"Allerød Gymnasium",
"Allikelund Gymnasium",
"Alssundgymnasiet Sønderborg",
"Birkerød Gymnasium ",
"Bjerringbro Gymnasium",
"Borupgaard Gymnasium",
"Borupgaard Gymnasium",
"Borupgaard Gymnasium",
"Brøndby Gymnasium",
"CELF",
"Christianhavns Gymnasium",
"Christianshavns Gymnasium",
"CPH West",
"Det Fri Gymnasium",
"Det Kristne GYmnasium",
"Dronninglund Gymnasium",
"Egaa Gymnasium",
"Esbjerg Gymnasium & HF",
"EUC Lillebælt",
"Faaborg Gymnasium",
"Favrskov Gymnasium",
"Favrskov Gymnasium",
"Fjerritslev Gymnasium",
"Fredericia Gymnasium",
"Frederiksborg Gymnasium & HF",
"Frederikshavn Gymnasium & HF",
"Frederikssund Gymnasium",
"Gefion Gymnasium",
"Gentofte HF",
"Gl. Hellerup Gymnasium",
"Grenaa Gymnasium",
"Greve Gymnasium",
"Greve Gymnasium",
"GUX -Sisimiut",
"Haderslev Katedralskole",
"Haderslev Katedralskole",
"Hasseris Gymnasium",
"HC Ørsted Gymnasium",
"Helsingør Gymnasium",
"Herlev Gymnasium & HF",
"Herlufsholm",
"Herlufsholm",
"Herning Gymnasium",
"HF & VUC Fyn",
"HF & VUC Kbh. Syd",
"HF & VUC Klar",
"HF & VUC Nordsjælland",
"Hillerød Handelsgymnasium",
"Horsens Gymnasium & HF",
"Horsens HF & VUC",
"Horsens Statsskole",
"Hovedstadens Kristne Gymnasium",
"HTX Roskilde",
"HTX Skjern",
"Kold College",
"Kolding Gymnasium",
"Kolding HF & VUC",
"Kolding HF & VUC",
"Købehavns Private Gymnasium",
"Københavns Åbne Gymnasium",
"Køge Gymnasium",
"Køge Gymnasium",
"Langkær Gymnasium",
"Lemvig Gymnasium",
"Mariagerfjord Gymnasium",
"Maribo Gymnasium",
"Marie Kruse Gymnasium",
"Marie Kruses Skole",
"Marselisborg Gymnasium",
"Middelfart Gymnasium",
"Midtsjællands Gymnasium",
"Morsø Gymnasium",
"Mulernes Legatskole",
"Munkensdam Gymnasium",
"N. Zahles Skole",
"Niels Steensens Gymnasium",
"Nordfyns Gymnasium",
"Nordsjællands HF & VUC",
"Nykøbing Katedralskole",
"Nørre Gymnasium",
"Nørresundby Gymnasium & HF",
"Nørresundby Gymnasium & HF",
"Odense Katedralskole",
"Odense Tekniske Gymnasium",
"Odsherred Gymnasium",
"Paderup Gymnasium",
"Randers Statsskole",
"Randers Statsskole",
"Ribe Katedralskole",
"Ribe Katedralskole",
"RingkJøbing Gymnasium",
"Risskov Gymnasium",
"Roskilde Handelsgymnasium",
"Roskilde Katedralskole",
"Rybners",
"Rybners Gymnasium",
"Rødkilde Gymnasium",
"Rødovre Gymnasium",
"Rønde Gymnasium",
"Sankt Annæ Gymnasium",
"Sct. Knuds Gymnasium",
"SCU",
"Silkeborg Gymnasium",
"Skanderborg Gymnasium",
"Skive Gymnasium & HF",
"Skive Tekniske Skole",
"Skive Tekniske Skole",
"Slagelse Gymnasium",
"Sorø Akademis Skole",
"Student Media ApS",
"Støvring Gymnasium",
"Sønderborg Statsskole",
"Taastrup Gymnasium",
"Teknisk Gymnasium Silkeborg",
"Thisted Gymnasium",
"Thy-Mors HF & VUC",
"Tornbjerg Gymnasium",
"Tornbjerg Gymnasium",
"Tornbjerg Gymnasium",
"Tårnby Gymnasium",
"Tønder Gymnasium",
"Tørring Gymnasium",
"Uddannelsescenter Ringkøbing Skjern",
"Varde Gymnasium",
"Vejen Gymnasium & HF",
"Vejlefjordskolen",
"Vestegnen HF & VUC",
"Vesthimmerlands Gymnasium & HF",
"Vestjysk Gymnasium Tarm",
"Viborg Katedralskole",
"Viby Gymnasium",
"Virum Gymnasium",
"Vordingborg Gymnasium",
"VUC & HF Nordjylland",
"VUC Vestsjælland Syd",
"Øregård Gymnasium",
"Ørestad Gymnasium",
"Ørestad Gymnasium",
],
"Seminarier": [
"Blaagaard Seminarium",
"Læreruddannelsen Aalborg",
"Læreruddannelsen Aarhus",
"Læreruddannelsen Bornholm",
"Læreruddannelsen Lillebælt",
"Læreruddannelsen og HF i Nørre Nissum",
"Læreruddannelsen på Fyn",
"Læreruddannelsen Roskilde",
"Læreruddannelsen Vordingborg",
"Læreruddannelsen Zahle",
]
}