var schools = {
    "Gymnasier": [
	"Allerød Gymnasium",
	"Alssundgymnasiet Sønderborg",
	"Aurehøj Gymnasium",
	"Birkerød Gymnasium HF IB & Kostskole",
	"Bjerringbro Gymnasium",
	"Borupgaard Gymnasium",
	"Brønderslev Gymnasium og HF",
	"Campus Bornholm - STX",
	"Christianshavns Gymnasium",
	"CPH",
	"Dronninglund Gymnasium",
	"Duborg-Skolen",
	"Egedal Gymnasium & HF",
	"Egå Gymnasium",
	"Esbjerg Gymnasium og HF Kursus",
	"Espergærde Gymnasium og HF",
	"Falkonergårdens Gymnasium og HF-Kursus",
	"Favrskov Gymnasium",
	"Fjerritslev Gymnasium",
	"Fredericia Gymnasium",
	"Frederiksberg Gymnasium",
	"Frederiksberg HF-Kursus",
	"Frederiksborg Gymnasium og HF",
	"Frederikshavn Gymnasium og HF-Kursus",
	"Frederikssund Gymnasium",
	"Frederiksværk Gymnasium og HF",
	"Faaborg Gymnasium",
	"Fyns HF",
	"Fyns HF-Kursus",
	"Gammel Hellerup Gymnasium",
	"Gefion Gymnasium",
	"Gentofte HF",
	"Gladsaxe Gymnasium",
	"Grenaa Gymnasium",
	"Greve Gymnasium",
	"Gribskov Gymnasium",
	"Grindsted Gymnasium & HF",
	"GUX Nuuk",
	"Haderslev Katedralskole",
	"Hasseris Gymnasium",
	"Helsingør Gymnasium",
	"Herlev Gymnasium og HF",
	"Herning Gymnasium",
	"HF-Centret Efterslægten",
	"Himmelev Gymnasium",
	"Hjørring Gymnasium og HF-Kursus",
	"Holstebro Gymnasium og HF",
	"Horsens Gymnasium",
	"Horsens Statsskole - Gymnasium og HF-Kursus",
	"HTX-Hillerød",
	"HTX Sukkertoppen",
	"Hvidovre Gymnasium & HF",
	"Høje-Taastrup Gymnasium",
	"Høng Gymnasium og HF",
	"Ikast-Brande Gymnasium",
	"Kalundborg Gymnasium og HF",
	"Kolding Gymnasium HF-Kursus og IB School",
	"Kongsholm Gymnasium & HF",
	"Københavns VUC",
	"Københavns åbne Gymnasium",
	"Køge Gymnasium",
	"Langkær Gymnasium og HF",
	"Lemvig Gymnasium",
	"Lemvig Gymnasium",
	"Mariagerfjord Gymnasium",
	"Maribo Gymnasium",
	"Marselisborg Gymnasium",
	"Middelfart Gymnasium og HF-Kursus",
	"Midtfyns Gymnasium",
	"Midtsjællands Gymnasium",
	"Ringsted Gymnasium",
	"Haslev Gymnasium og HF",
	"Morsø Gymnasium",
	"Mulernes Legatskole",
	"Munkensdam Gymnasium",
	"Nakskov Gymnasium og HF",
	"Nordfyns Gymnasium",
	"Nyborg Gymnasium",
	"Nykøbing Katedralskole",
	"Nærum Gymnasium",
	"Næstved Gymnasium og HF",
	"Nørre Gymnasium",
	"Nørresundby Gymnasium og HF",
	"Odder Gymnasium",
	"Odense Katedralskole",
	"Odsherreds Gymnasium",
	"Ordrup Gymnasium",
	"Paderup Gymnasium",
	"Randers Statsskole",
	"Ribe Katedralskole",
	"Ringkjøbing Gymnasium",
	"Risskov gymnasium",
	"Rosborg Gymnasium & HF",
	"Roskilde Gymnasium",
	"Roskilde Katedralskole",
	"Rungsted Gymnasium",
	"Rybners Gymnasium HHX og STX",
	"Rysensteen Gymnasium",
	"Rødkilde Gymnasium",
	"Rødovre Gymnasium",
	"Rønde Gymnasium",
	"Sankt Annæ Gymnasium",
	"Sct. Knuds Gymnasium",
	"Silkeborg Gymnasium",
	"Skanderborg Gymnasium",
	"Skive Gymnasium og HF",
	"Slagelse Gymnasium",
	"Solrød Gymnasium",
	"Sorø Akademis Skole",
	"Stenhus Gymnasium og HF",
	"Struer Statsgymnasium",
	"Struer Statsgymnasium",
	"Støvring Gymnasium",
	"Svendborg Gymnasium og HF",
	"Sønderborg Statsskole",
	"Teknisk Gymnasium Silkeborg",
	"Thisted Gymnasium og HF-Kursus",
	"TH. LANGS HF-KURSUS",
	"Tornbjerg Gymnasium",
	"Tønder Gymnasium",
	"Tørring Gymnasium",
	"Tårnby Gymnasium",
	"Varde Gymnasium",
	"Vejen Gymnasium og HF",
	"Vestfyns Gymnasium",
	"Vesthimmerlands Gymnasium og HF",
	"Vestjysk Gymnasium Tarm",
	"Vestjysk Gymnasium Tarm",
	"Viborg Gymnasium og HF",
	"Viborg Katedralskole",
	"Viby Gymnasium",
	"Virum Gymnasium",
	"Vordingborg Gymnasium & HF",
	"Øregård Gymnasium",
	"Ørestad Gymnasium",
	"Århus Akademi",
	"Århus Statsgymnasium",
	"Aabenraa Statsskole",
	"Aalborg Katedralskole",
	"Aalborghus Gymnasium",
	"Aarhus Gymnasium",
	"Aarhus Katedralskole"
    ],

    "Private gymnasier og HF-kurser": [
	"Bagsværd Kostskole og Gymnasium",
	"Brøndby Gymnasium",
	"Copenhagen International School",
	"Det frie Gymnasium",
	"Det Kristne Gymnasium",
	"Deutsches Gymnasium Für Nordschleswig",
	"Herlufsholm Skole og Gods",
	"Ingrid Jespersens Gymnasieskole",
	"Johannesskolen",
	"Københavns Private Gymnasium",
	"Køge Private",
	"Marie Kruses Skole",
	"Niels Steensens Gymnasium",
	"Nordsjællands Grundskole og Gymnasium samt HF",
	"N. Zahles Gymnasieskole",
	"Oure Idrætsgymnasium",
	"Prins Henriks",
	"Sankt Petri skole - Gymnasium",
	"Vejlefjordskolen"
    ],

    "Studenterkurser": [
	"Akademisk Studenterkursus",
	"Gentofte Studenterkursus",
	"Studenterkurset og Kostskolen i Sønderjylland",
	"Østerbro International School",
	"Aalborg Studenterkursus",
    ],

    "Seminarier": [
	"Læreruddannelsen Bornholm",
	"Læreruddannelsen Aalborg",
	"Læreruddannelsen Zahle",
	"Læreruddannelsen Aarhus",
	"Læreruddannelsen Vordingborg",
	"Læreruddannelsen og HF i Nørre Nissum",
	"Læreruddannelsen på Fyn",
    ],

    "Andre": [
	"Hotel- og Restaurantskolen",
	"Stevns Kommune"
    ],

    "Skriv til yubio@yubio.dk, hvis du vil på listen" : [
	"Andet"
    ]
}
