var schools = {
"Gymnasier": [
"Aalborghus Gymnasium",
"Aarhus Handelsgymnasium",
"Aarhus HF & VUC",
"Aarhus Statsgymnasium",
"Allerød Gymnasium",
"Alssundgymnasiet Sønderborg",
"Birkerød Gymnasium ",
"Bjerringbro Gymnasium",
"Borupgaard Gymnasium",
"Borupgaard Gymnasium",
"Borupgaard Gymnasium",
"Brøndby Gymnasium",
"CELF",
"Christianhavns Gymnasium",
"Christianshavns Gymnasium",
"CPH West",
"Det Fri Gymnasium",
"Det Kristne Gymnasium",
"Egå Gymnasium",
"Esbjerg Gymnasium & HF",
"EUC Lillebælt",
"EUC Syd",
"Faaborg Gymnasium",
"Favrskov Gymnasium",
"Favrskov Gymnasium",
"Fjerritslev Gymnasium",
"Fredericia Gymnasium",
"Frederiksborg Gymnasium & HF",
"Frederikshavn Gymnasium & HF",
"Gefion Gymnasium",
"Gentofte HF",
"Gl. Hellerup Gymnasium",
"Grenaa Gymnasium",
"Greve Gymnasium",
"Greve Gymnasium",
"GUX -Sisimiut",
"Haderslev Katedralskole",
"Haderslev Katedralskole",
"Helsingør Gymnasium",
"Herlev Gymnasium & HF",
"Herlufsholm",
"Herlufsholm",
"Herning Gymnasium",
"Herning HF & VUC",
"Herningsholm Erhvervsskole & Gymnasier",
"HF & VUC Nordsjælland",
"Hillerød Handelsgymnasium",
"Hjørring Gymnasium",
"Horsens Gymnasium & HF",
"Horsens HF & VUC",
"Horsens Statsskole",
"Hovedstadens Kristne Gymnasium",
"HTX Roskilde",
"HTX Skjern",
"IBC",
"Ikast-Brande Gymnasium",
"Ingrid Jespersens Gymnasieskole",
"Kalundborg Gymnasium & HF",
"Kold College",
"Kold College",
"Kolding Gymnasium",
"Kolding HF & VUC",
"Kolding HF & VUC",
"Købehavns Private Gymnasium",
"Københavns Idrætsefterskole",
"Københavns Private Gymnasium",
"Køge Gymnasium",
"Køge Gymnasium",
"Langkær Gymnasium",
"Lemvig Gymnasium",
"Mariagerfjord Gymnasium",
"Maribo Gymnasium",
"Marie Kruse Gymnasium",
"Marie Kruses Skole",
"Marselisborg Gymnasium",
"Mercantec",
"Middelfart Gymnasium",
"Midtsjællands Gymnasium",
"Morsø Gymnasium",
"Mulernes Legatskole",
"Munkensdam Gymnasium",
"Niels Steensens Gymnasium",
"Nordfyns Gymnasium",
"Nordsjællands HF & VUC",
"Nyborg Gymnasium",
"Nykøbing Katedralskole",
"Næstved Gymnasium & HF",
"Nørre Gymnasium",
"Nørrebro Gymnasium",
"Nørresundby Gymnasium & HF",
"Nørresundby Gymnasium & HF",
"Odense Katedralskole",
"Odense Tekniske Gymnasium",
"Odsherred Gymnasium",
"Paderup Gymnasium",
"Randers Statsskole",
"Randers Statsskole",
"Ribe Katedralskole",
"Ribe Katedralskole",
"RingkJøbing Gymnasium",
"Risskov Gymnasium",
"Rosborg Gymnasium & HF",
"Roskilde Gymnasium",
"Roskilde Handelsgymnasium",
"Roskilde Katedralskole",
"Rybners",
"Rybners Gymnasium",
"Rødkilde Gymnasium",
"Rødovre Gymnasium",
"Rønde Gymnasium",
"Sankt Annæ Gymnasium",
"Sct. Knuds Gymnasium",
"Silkeborg Gymnasium",
"Skanderborg Gymnasium",
"Skive Gymnasium & HF",
"Skive Tekniske Skole",
"Skive Tekniske Skole",
"Slagelse Gymnasium",
"Sorø Akademis Skole",
"Struer Statsgymnasium",
"Student Media ApS",
"Støvring Gymnasium",
"Sydkystens Gymnasium",
"Sønderborg Statsskole",
"Teknisk Gymnasium Silkeborg",
"Thisted Gymnasium",
"Thy-Mors HF & VUC",
"Tornbjerg Gymnasium",
"Tornbjerg Gymnasium",
"Tornbjerg Gymnasium",
"Tårnby Gymnasium",
"Tønder Gymnasium",
"Tørring Gymnasium",
"Uddannelsescenter Ringkøbing Skjern",
"Varde Gymnasium",
"Vejen Gymnasium & HF",
"Vejlefjordskolen",
"Vesthimmerlands Gymnasium & HF",
"Viborg Gymnasium & HF",
"Viborg Katedralskole",
"Viby Gymnasium",
"Virum Gymnasium",
"Vordingborg Gymnasium",
"VUC & HF Nordjylland",
"VUC Vestsjælland Syd",
"Århus Akademi",
"Århus Statsgymnasium",
"Øregård Gymnasium",
"Ørestad Gymnasium",
"Ørestad Gymnasium",
],
"Seminarier": [
"Blaagaard Seminarium",
"Læreruddannelsen Aalborg",
"Læreruddannelsen Aarhus",
"Læreruddannelsen Bornholm",
"Læreruddannelsen Lillebælt",
"Læreruddannelsen og HF i Nørre Nissum",
"Læreruddannelsen på Fyn",
"Læreruddannelsen Roskilde",
"Læreruddannelsen Vordingborg",
"Læreruddannelsen Zahle",
]
}