var links = {
  "Videos":[
	{"chapter":"1", "caption": "Prokaryoter og eukaryoter ", "link": "", "color":"#26213B"},
	{"chapter":"1","caption": "Membranprocesser",	"link": "","color":"#26213B"},
	{"chapter":"2","caption": "Åndedræt og blodkredsløb", "link": "","color":"#26213B"},
	{"chapter":"3","caption": "Fordøjelsen", "link": "","color":"#26213B"},	
	{"chapter":"5","caption": "Immunforsvaret", "link": "","color":"#26213B"},	
	{"chapter":"6","caption": "Hormonregulering", "link": "","color":"#26213B"},	
	{"chapter":"8","caption": "Aktionspotentialet", "link": " https://www.youtube.com/watch?v=mC0j49GoYss","color":"#26213B"},
    {"chapter":"8","caption": "Synapsen", "link": "www.youtube.com/watch?v=v1twCQR-8vo","color":"#26213B"},
    {"chapter":"9","caption": "Musklernes opbygning og funktion", "link": "","color":"#26213B"},
    {"chapter":"10","caption": "Energiproduktion under arbejde", "link": "","color":"#26213B"},
     {"chapter":"13","caption": "Kulhydrater", "link": "", "color":"#5E6BAF"},
    {"chapter":"14","caption": "Fedtstoffer", "link": "","color":"#5E6BAF"},
     {"chapter":"15","caption": "Aminosyrer og proteiner", "link": "","color":"#5E6BAF"},
    {"chapter":"16","caption": "Enzymer og enzymgrupper", "link": "","color":"#5E6BAF"},
     {"chapter":"17","caption": "Respiration af kulhydrater", "link": "","color":"#5E6BAF"},
    {"chapter":"18","caption": "Fotosyntesen", "link": "","color":"#5E6BAF"},
    {"chapter":"19","caption": "Genom og DNA", "link": "https://www.youtube.com/watch?v=FjTERzMIylw","color":"#6BC2B8"},
   {"chapter":"20","caption": "Proteinsyntesen (basic) ", "link": "https://www.youtube.com/watch?v=nIsIXLO0yl0","color":"#6BC2B8"},
{"chapter":"20","caption":"Splicing","link": "https://www.youtube.com/watch?v=0dKD_CmMhsg","color":"#6BC2B8"},
{"chapter":"21","caption":"Autosomal etgens nedarvning (kort)","link":"https://www.youtube.com/watch?v=BNjV_vTVPHE","color":"#6BC2B8"},
{"chapter":"21","caption":"Autosomal etgens nedarvning (lang)","link": "https://www.youtube.com/watch?v=eEcnc_cFxq8","color":"#6BC2B8"},
{"chapter":"21","caption":"Kønsbundet nedarvning","link":"https://www.youtube.com/watch?v=LmbD08wERp4","color":"#6BC2B8"},
{"chapter":"21","caption":"Autosomal togens nedarvning (kort)","link":"https://www.youtube.com/watch?v=mnojjG3E3l4","color":"#6BC2B8"},
{"chapter":"21","caption":"Autosomal togens nedarvning (lang)","link":"https://www.youtube.com/watch?v=ON3UV_u9jq0","color":"#6BC2B8"},
{"chapter":"22","caption":"Mutationer", "link":"","color":"#6BC2B8"},
{"chapter":"23","caption":"Grundlæggende genteknologi", "link":"","color":"#6BC2B8"},
{"chapter":"24","caption":"Bioinformatik","link":"","color":"#6BC2B8"},
{"chapter":"26","caption":"Populationsbiologi", "link":"","color":"#EC641C"},
{"chapter":"27","caption":"Kredsløb","link":"","color":"#EC641C"},
{"chapter":"29","caption":"Søen som økosystem","link":"","color":"#EC641C"},
{"chapter":"30","caption":"Vandforurening og økotoksikologi","link":"","color":"#EC641C"}
]
}
