var links = {
    "5": [

		{"caption": "Befrugtning (og prævention)", "link": "https://www.youtube.com/watch?v=SUdAEGXLO-8"},
{"caption": "Kvindens kønsorganer", "link": "https://www.youtube.com/watch?v=RFDatCchpus"},
{"caption": "Mandens kønsorganer", "link": "https://www.youtube.com/watch?v=-XQcnO4iX_U"},

{"caption": "AIDS", "link": "http://blausen.com/da/video/aids/"},
{"caption": "Amning", "link": "http://blausen.com/da/video/amning/"},
{"caption": "Brystets funktion", "link": "http://blausen.com/da/video/brystets-funktion/"},
{"caption": "Brystforstørrelse", "link": "http://blausen.com/da/video/brystforstrrelse/"},
{"caption": "Brystreduktion", "link": "http://blausen.com/da/video/brystreduktion/"},
{"caption": "Bumser", "link": "http://blausen.com/da/video/bumser-akne/"},
{"caption": "Celleforandringer i livmoderen", "link": "http://blausen.com/da/video/celleforandringer-i-livmoderhalsen/"},
{"caption": "Downs syndrom", "link": "http://blausen.com/da/video/downs-syndrom/"},
{"caption": "Endometriose", "link": "http://blausen.com/da/video/endometriose/"},
{"caption": "Fjernelse af livmoderen", "link": "http://blausen.com/da/video/fjernelse-af-livmoderen-hysterektomi/"},
{"caption": "Fjernelse af prostata", "link": "http://blausen.com/da/video/fjernelse-af-prostata/"},
{"caption": "Fjernelse af æggestokke", "link": "http://blausen.com/da/video/fjernelse-af-æggestokke/"},
	{"caption": "Fosterudvikling",
	 "link": "http://www.hhmi.org/biointeractive/human-embryonic-development"},
	{"caption": "Fosterudvikling 2", "link": "http://blausen.com/da/video/fosterudvikling/"},
	{"caption": "Fosterudvikling 3", "link": "https://www.youtube.com/watch?v=BtsSbZ85yiQ"},
 	{"caption": "Fosterudvikling og risiko",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter20/animation__fetal_development_and_risk.html"},
{"caption": "Fostervandsprøve", "link": "http://blausen.com/da/video/fostervandsprve-amniocentese/"},
{"caption": "Fostervandsprøve", "link": "http://blausen.com/da/video/fostervandsprve-amniocentese/"},
{"caption": "Fødsel med sugekop", "link": "http://blausen.com/da/video/assisteret-fdsel-sugekop/"},
{"caption": "Fødsel", "link": "http://blausen.com/da/video/fdsel/"},
{"caption": "Graviditet uden for livmoderen", "link": "http://blausen.com/da/video/graviditet-udenfor-livmoderen/"},
{"caption": "Herpes", "link": "http://blausen.com/da/video/herpes/"},
{"caption": "Impotens", "link": "http://blausen.com/da/video/impotens/"},
{"caption": "Kejsersnit", "link": "http://blausen.com/da/video/kejsersnit/"},
{"caption": "Kræft i æggestokkene", "link": "http://blausen.com/da/video/ggestokkrft/"},
{"caption": "Kunstig befrugtning", "link": "http://blausen.com/da/video/kunstig-befrugtning/"},
{"caption": "Livmoderkræft", "link": "http://blausen.com/da/video/livmoderkræft/"},
{"caption": "Menopause", "link": "http://blausen.com/da/video/ophør-af-menstruation-menopause/"},
{"caption": "Moderkagebiopsi", "link": "http://blausen.com/da/video/moderkageprve/"},
{"caption": "P-plaster", "link": "http://blausen.com/da/video/p-plaster/"},
{"caption": "PMS", "link": "http://blausen.com/da/video/prmenstruelt-syndrom-pms/"},
{"caption": "Penisimplantat", "link": "http://blausen.com/da/video/penisimplantat/"},
{"caption": "Prostatakræft", "link": "http://blausen.com/da/video/prostatakrft/"},
{"caption": "Spiral", "link": "http://blausen.com/da/video/spiral/"},
{"caption": "Sterilisation af mænd", "link": "http://blausen.com/da/video/sterilisering-af-mnd-vasektomi/"},
{"caption": "Svamp i skeden", "link": "http://blausen.com/da/video/svampeinfektion-i-skeden/"},
{"caption": "Tyktarmskræft", "link": "http://blausen.com/da/video/tyktarmskræft/"},
{"caption": "Ultralyd og graviditet", "link": "http://blausen.com/da/video/ultralyd-under-graviditeten/"},
{"caption": "Underlivsbetændelse", "link": "http://blausen.com/da/video/underlivsbetndelse/"},
{"caption": "Undersøg brysterne selv", "link": "http://blausen.com/da/video/undersøg-brysterne-selv/"},
{"caption": "Urinvejsinfektion", "link": "http://blausen.com/da/video/urinvejsinfektion/"},


	{"caption": "Naturlig selektion",
	 "link": "http://www.hhmi.org/biointeractive/natural-selection-lactose-tolerance"},
	{"caption": "Hjernens udvikling",
	 "link": "http://www.hhmi.org/biointeractive/development-human-embryonic-brain"},
	{"caption": "Negativt feedback",
	 "link": "http://highered.mheducation.com/sites/0072495855/student_view0/chapter20/animation__positive_and_negative_feedback__quiz_1_.html"},

	{"color": "#6DC0B4"},

	{"caption": "Risikable P-piller",
	 "link": "http://politiken.dk/forbrugogliv/sundhedogmotion/ECE2816488/120000-kvinder-spiser-de-mest-risikable-p-piller/"},

	{"caption": "Netdoktor",
	 "link": "http://www.netdoktor.dk"},
	{"caption": "Sundhedsguiden",
	 "link": "http://www.sundhedsguiden.dk"},
	{"caption": "Sundhed",
	 "link": "http://www.sundhed.dk"},
	{"caption": "Videnskab.dk",
	 "link": "http://www.videnskab.dk"},
	{"caption": "Sex og samfund",
	 "link": "http://www.sexogsamfund.dk"},
	{"caption": "Forældre og fødsel",
	 "link": "http://www.fogf.dk"},
	{"caption": "Etisk råd",
	 "link": "http://www.etiskraad.dk"},
	{"caption": "AIDS-fondet",
	 "link": "http://www.aidsfondet.dk"},
	{"caption": "Aktuel Naturvidenskab",
	 "link": "http://aktuelnaturvidenskab.dk"},
	{"caption": "Etik.dk",
	 "link": "http://www.etik.dk/abort"},
	{"caption": "Prævention",
	 "link": "http://www.netdoktor.dk/sex_samliv/praevention.shtml"},
	{"caption": "Kønssygdomme",
	 "link": "http://www.sundhedsguiden.dk/da/temaer/alle-temaer/koenssygdomme/"},
	{"caption": "Andre seksuelt overførte sygdomme",
	 "link": "http://www.sundhedsguiden.dk/da/temaer/alle-temaer/sex-og-samliv/seksualundervisning/andre-seksuelt-overf-oslash;rte-sygdomme/"},
	{"caption": "HIV/AIDS",
	 "link": "http://min.medicin.dk/Sygdomme/Sygdom/56"}
    ]
}
