var links = {
    "3": [

		{"caption": "De indre organer", "link": "https://www.youtube.com/watch?v=jGme7BRkpuQ"},
{"caption": "Fra mund til mave", "link": "https://www.youtube.com/watch?v=fR3NxCR9z2U"},
{"caption": "Kost og energi", "link": "https://www.youtube.com/watch?v=fR3NxCR9z2U"},
	{"caption": "Fordøjelsen 3", "link": "https://www.youtube.com/watch?v=s06XzaKqELk"},
	{"caption": "Fedme og helbredsproblemer",
	 "link": "http://www.hhmi.org/biointeractive/obesity-related-health-problems"},
	{"caption": "Fedt og fedtfordøjelse og energioplagring",
	 "link": "http://www.hhmi.org/biointeractive/fate-fat"},
	{"caption": "BMI",
	 "link": "http://www.hhmi.org/biointeractive/body-mass-index-bmi"},

	{"caption": "Fordøjelseskanalen 2", "link": "https://www.youtube.com/watch?v=yIoTRGfcMqM"},

	 {"caption": "Kan mad være sundt eller usundt?",
	 "link": "https://altomkost.dk/fakta/myterommad/sundtogusundt/"},
	 {"caption": "Skal du droppe kulhydrater?",
	 "link": "https://altomkost.dk/fakta/myterommad/feder-kulhydrater/"},
	 {"caption": "Fedtforherligelse eller fedtforskrækkelse",
	 "link": "https://altomkost.dk/fakta/myterommad/feder-kulhydrater/"},
	{"color": "#6DC0B4"},

	{"caption": "Danskernes sundhed",
	 "link": "http://www.danskernessundhed.dk"},
	{"caption": "Ulighedens Danmarkskort",
	 "link": "http://cevea.dk/ulighedens-danmarkskort"},
	{"caption": "Kostanalyse 1",
	 "link": "https://cronometer.com"},
	{"caption": "Kostanalyse 2",
	 "link": "http://www.madital.dk"},
	{"caption": "Netdoktor",
	 "link": "http://www.netdoktor.dk"},
	{"caption": "Sundhedsguiden",
	 "link": "http://www.sundhedsguiden.dk"},
	{"caption": "Sundhed",
	 "link": "http://www.sundhed.dk"},
	{"caption": "Videnskab.dk",
	 "link": "http://www.videnskab.dk"},
	{"caption": "Sundhedsstyrelsen",
	 "link": "http://sundhedsstyrelsen.dk"},
	{"caption": "Min medicin",
	 "link": "http://www.min.medicin.dk"},
	{"caption": "Videnskab.dk",
	 "link": "http://www.videnskab.dk"},
	{"caption": "Aktuel Naturvidenskab",
	 "link": "http://aktuelnaturvidenskab.dk"},
	{"caption": "Alt om kost",
	 "link": "http://altomkost.dk/raad-og-anbefalinger/de-officielle-kostraad/"},
	 
    ]
}
