var links = {
    "10": [
	{"caption": "Menneskeskabt effekt",
	 "link": "http://www.bloomberg.com/graphics/2015-whats-warming-the-world/"},
	{"caption": "Eutrofiering",
	 "link": "https://www.youtube.com/watch?v=6LAT1gLMPu4"},
	{"caption": "Drivhuseffekt 1",
	 "link": "http://www.hhmi.org/biointeractive/greenhouse-effect"},
	{"caption": "Drivhuseffekt 2",
	 "link": "https://www.youtube.com/watch?v=NPXVKb-k2nU"},
	{"caption": "Koralblegning",
	 "link": "http://www.hhmi.org/biointeractive/coral-bleaching"},
	{"caption": "Klimaeffekter/globalopvarmning",
	 "link": "https://www.youtube.com/watch?v=FooW41rlP9A"},
	{"caption": "Klimaforandringer",
	 "link": "https://www.youtube.com/watch?v=dph2SVhDFAg"},

	{"color": "#6DC0B4"},

	{"caption": "Videnskab.dk",
	 "link": "http://www.videnskab.dk"},
	{"caption": "Miljøstyrelsen",
	 "link": "http://mst.dk"},
	{"caption": "PCB Guiden",
	 "link": "http://pcb-guiden.dk"},
	{"caption": "De danske vandværker",
	 "link": "http://www.dkvand.dk/index1.htm"},
	{"caption": "Det nye Arktis",
	 "link": "http://www.detnyearktis.dk"},
	{"caption": "Greenpeace",
	 "link": "http://www.greenpeace.org/international/en/"},
	{"caption": "Klimadebat",
	 "link": "http://www.klimadebat.dk"},
	{"caption": "EDGAR",
	 "link": "http://edgar.jrc.ec.europa.eu/index.php"},
	{"caption": "Vandstandskort",
	 "link": "http://flood.firetree.net"},
	{"caption": "Aktuel Naturvidenskab",
	 "link": "http://aktuelnaturvidenskab.dk"},
	{"caption": "Danske søer og deres restaurering",
	 "link": "http://www2.dmu.dk/1_viden/2_publikationer/3_temarapporter/rapporter/87-7772-440-2.pdf"},
	{"caption": "Vandets vej",
	 "link": "http://www.vandetsvej.dk/RENSEANLÆG-55.aspx"},
	{"caption": "Naturstyrelsen",
	 "link": "http://naturstyrelsen.dk"},
	{"caption": "Danmarks Miljøportal",
	 "link": "http://www.miljoeportal.dk/Sider/Forside.aspx"}
    ]
}
