var links = {
    "7": [
	{"caption": "Nedarvning", "link": "https://www.youtube.com/watch?v=8kK2zwjRV0M"},

	{"caption": "DNA-replikation",
	 "link": "http://www.hhmi.org/biointeractive/dna-replication-basic-detail"},
	{"caption": "DNA og replikation", "link": "https://www.youtube.com/watch?v=8kK2zwjRV0M"},
	{"caption": "Mitose", "link": "https://www.youtube.com/watch?v=aTftyFboC_M"},
	{"caption": "Meiose 1",
	 "link": "http://vcell.ndsu.nodak.edu/animations/meiosis/movie-flash.htm"},
	{"caption": "Meiose 2",
	 "link": "http://highered.mheducation.com/olc/dl/120074/bio19.swf"},
	{"caption": "Meiose 3",
	 "link": "http://www.youtube.com/watch?v=D1_-mQS_FZ0&feature=related"},
	{"caption": "Mitose 1",
	 "link": "http://vcell.ndsu.nodak.edu/animations/mitosis/movie-flash.htm"},
	{"caption": "Mitose 2",
	 "link": "http://highered.mheducation.com/olc/dl/120073/bio14.swf"},
	{"caption": "Mitose 3",
	 "link": "http://www.youtube.com/watch?v=VlN7K1-9QB0"},
	{"caption": "Mitose 4",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter3/animation__mitosis_and_cytokinesis.html"},
	{"caption": "Mitose & meiose",
	 "link": "https://www.youtube.com/watch?v=Ba9LXKH2ztU"},
	{"caption": "Mitose vs. Meiose",
	 "link": "http://highered.mheducation.com/olc/dl/120074/bio17.swf"},
	{"caption": "DNA 1",
	 "link": "http://highered.mheducation.com/sites/dl/free/0072835125/126997/animation12.html"},
	{"caption": "DNA 2",
	 "link": "http://www.hhmi.org/biointeractive/chemical-structure-dna"},
	{"caption": "DNA 3",
	 "link": "http://www.hhmi.org/biointeractive/paired-dna-strands"},
	{"caption": "Bygge DNA",
	 "link": "http://learn.genetics.utah.edu/content/molecules/builddna/"},
	{"caption": "DNA og histoner",
	 "link": "http://www.hhmi.org/biointeractive/dna-packaging"},
	{"caption": "DNA-replikation",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter3/animation__dna_replication__quiz_1_.html"},
	{"caption": "Genomet",
	 "link": "http://www.dnalc.org/resources/3d/09-how-much-dna-codes-for-protein.html"},
	{"caption": "Transkription og translation", "link": "https://www.youtube.com/watch?v=aTftyFboC_M"},
	{"caption": "Transkription 1",
	 "link": "http://vcell.ndsu.nodak.edu/animations/transcription/movie-flash.htm"},
	{"caption": "Transkription 2",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter3/animation__mrna_synthesis__transcription___quiz_1_.html"},
	{"caption": "Translation 1",
	 "link": "http://vcell.ndsu.nodak.edu/animations/translation/movie-flash.htm"},
	{"caption": "Translation 2",
	 "link": "http://www.hhmi.org/biointeractive/translation-basic-detail"},
 	{"caption": "Translation 3",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter2/animation__protein_synthesis__quiz_2_.html"},
	{"caption": "Transkription og translation",
	 "link": "http://www.dnalc.org/resources/3d/central-dogma.html"},
	{"caption": "Den genetiske kode",
	 "link": "http://www.hhmi.org/biointeractive/triplet-code"},
	{"caption": "Proteinsyntese i eukaryter vs. Prokaryoter",
	 "link": "http://highered.mheducation.com/olc/dl/120077/bio25.swf"},
	{"caption": "Splicing",
	 "link": "http://vcell.ndsu.nodak.edu/animations/mrnasplicing/movie-flash.htm"},
	{"caption": "Splicing 2",
	 "link": "http://www.hhmi.org/biointeractive/mrna-splicing"},
	{"caption": "Due-spil om nedarvning",
	 "link": "http://learn.genetics.utah.edu/content/pigeons/pigeonetics/"},
	{"caption": "Blodtype-spil",
	 "link": "http://www.nobelprize.org/educational/medicine/bloodtypinggame/gamev2/index.html"},
	{"caption": "Epigenetik 1",
	 "link": "http://learn.genetics.utah.edu/content/epigenetics/control/"},
	{"caption": "Epigenetik 2",
	 "link": "http://learn.genetics.utah.edu/content/epigenetics/intro/"},
	{"caption": "Epigenetik 3",
	 "link": "http://learn.genetics.utah.edu/content/epigenetics/twins/"},

	{"color": "#6DC0B4"},

	{"caption": "Learn Genetics",
	 "link": "http://learn.genetics.utah.edu"},
	{"caption": "Yourgenome",
	 "link": "http://www.genome.gov"},
	{"caption": "Kræftens bekæmpelse",
	 "link": "http://www.cancer.dk"},
	{"caption": "Kennedy Centret",
	 "link": "http://www.kennedy.dk"},
	{"caption": "Videnskab.dk",
	 "link": "http://www.videnskab.dk"},
	{"caption": "Aktuel Naturvidenskab",
	 "link": "http://aktuelnaturvidenskab.dk"},
	{"caption": "HUGO-projektet",
	 "link": "http://web.ornl.gov/sci/techresources/Human_Genome/index.shtml"},
	{"caption": "Epigenetik",
	 "link": "http://www.biokemi.org/biozoom/issues/531/articles/2434"}    
    ]
}
