var links = {
    "4": [

{"caption": "Autonome nervesystem", "link": "https://www.youtube.com/watch?v=71pCilo8k4M"},
{"caption": "Centralnervesystemet", "link": "https://www.youtube.com/watch?v=QY9NTVh-Awo"},
{"caption": "Hjernen", "link": "https://www.youtube.com/watch?v=vHrmiy4W9C0"},
{"caption": "Intelligens", "link": "https://www.youtube.com/watch?v=1PLBmUVYYeg"},
{"caption": "Nervesystemet", "link": "https://www.youtube.com/watch?v=9fxm85Fy4sQ"},
{"caption": "Nervesystemet", "link": "https://www.youtube.com/watch?v=qPix_X-9t7E"},
{"caption": "Parasymtatiske nervesystem", "link": "https://www.youtube.com/watch?v=qqU-VjqjczE"},
{"caption": "Perifere nervesystem", "link": "https://www.youtube.com/watch?v=QY9NTVh-Awo"},
{"caption": "Sympatiske nervesystem", "link": "https://www.youtube.com/watch?v=0IDgBlCHVsA"},

{"caption": "ADHD", "link": "http://blausen.com/da/video/adhd/"},
{"caption": "ALS", "link": "http://blausen.com/da/video/amyotrofisk-lateralsklerose-als/"},
{"caption": "Alzheimer", "link": "http://blausen.com/da/video/alzheimers-sygdom/"},
{"caption": "Cystisk fibrose", "link": "http://blausen.com/da/video/cystisk-fibrose/"},
{"caption": "Depression", "link": "http://blausen.com/da/video/depression/"},
{"caption": "Epilepsi", "link": "http://blausen.com/da/video/epilepsi/"},
{"caption": "Migræne", "link": "http://blausen.com/da/video/migræne/"},
{"caption": "Multipel sklerose", "link": "http://blausen.com/da/video/multipel-sklerose/"},
{"caption": "Narkotikaafhængighed", "link": "http://blausen.com/da/video/narkotikaafhngighed/"},
{"caption": "Parkinsons syge", "link": "http://blausen.com/da/video/parkinsons-sygdom/"},

	{"caption": "Na-K-pumpen 1",
	 "link": "http://highered.mheducation.com/olc/dl/120068/bio03.swf"},
	{"caption": "Na-K-pumpen 2",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter3/animation__how_the_sodium_potassium_pump_works.html"},
	{"caption": "Aktionspotentialet",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter8/animation__the_nerve_impulse.html"},
	{"caption": "Aktionspotentialet 2 (AP)", "link": "https://www.youtube.com/watch?v=OZG8M_ldA1M"},
	{"caption": "AP",
	 "link": "http://highered.mheducation.com/olc/dl/120107/bio_d.swf"},
	{"caption": "Hvile og AP",
	 "link": "http://highered.mheducation.com/olc/dl/120107/anim0013.swf"},
	{"caption": "Synapsen 1",
	 "link": "http://www.hhmi.org/biointeractive/molecular-mechanism-synaptic-function"},
	{"caption": "Synapsen 2",
	 "link": "http://highered.mheducation.com/olc/dl/120107/anim0015.swf"},
	{"caption": "Synapsen 3",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter8/animation__chemical_synapse__quiz_1_.html"},
	{"caption": "Synapsen 4", "link": "https://www.youtube.com/watch?v=VitFvNvRIIY"},
	{"caption": "Mouse party",
	 "link": "http://learn.genetics.utah.edu/content/addiction/mouse/"},
	{"caption": "Lammelser pga. gift i synapsen",
	 "link": "http://www.hhmi.org/biointeractive/motor-cabal-toxins-block-motor-neuron-synapses"},

	{"caption": "Acetylkolins virkning",
	 "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter3/animation__receptors_linked_to_a_channel_protein.html"},

	{"color": "#6DC0B4"},

	{"caption": "Hjernesagen",
	 "link": "http://www.hjernesagen.dk"},
	{"caption": "Stofinfo",
	 "link": "http://stofinfo.sst.dk"},
	{"caption": "Videnskab.dk",
	 "link": "http://www.videnskab.dk"},
	{"caption": "Aktuel Naturvidenskab",
	 "link": "http://aktuelnaturvidenskab.dk"},
	{"caption": "Fantasy",
	 "link": "http://www.farma.ku.dk/index.php/Hvordan-virker-fantasy-i-hjern/2599/0/"},
	{"caption": "Kroppens egne cannabinoider",
	 "link": "http://www.farma.ku.dk/index.php/Kroppens-egne-cannabinoider-pa/2603/0/"}
    ]
}
