var links = {
    "8": [
        
	{"caption": "Ny gensplejset super-gær",
	 "link": "http://news.stanford.edu/news/2015/august/opioids-yeast-smolke-081315.html"},
	{"caption": "Isolering af DNA",
	 "link": "http://learn.genetics.utah.edu/content/labs/extraction/"},
	{"caption": "Gel-elektroforese",
	 "link": "http://learn.genetics.utah.edu/content/labs/gel/"},
	{"caption": "PCR 1",
	 "link": "http://learn.genetics.utah.edu/content/labs/pcr/"},
	{"caption": "PCR 2",
	 "link": "http://highered.mheducation.com/olc/dl/120078/micro15.swf"},
	{"caption": "PCR 3",
	 "link": "http://highered.mheducation.com/sites/dl/free/0072835125/126997/animation38.html"},
	{"caption": "PCR 4",
	 "link": "http://www.hhmi.org/biointeractive/polymerase-chain-reaction-pcr"},
	{"caption": "PCR 5",
	 "link": "http://www.hhmi.org/biointeractive/polymerase-chain-reaction"},
	{"caption": "Repetitivt DNA-metode",
	 "link": "http://highered.mheducation.com/sites/dl/free/0072835125/126997/animation40.html"},
	{"caption": "RFLP",
	 "link": "http://highered.mheducation.com/olc/dl/120078/bio20.swf"},
	{"caption": "Mutationer",
	 "link": "https://www.youtube.com/watch?v=xYOK-yzUWSI"},
	{"caption": "Mutations-effekter",
	 "link": "https://www.youtube.com/watch?v=JxC2phkdY8Y"},
	{"caption": "Kloning",
	 "link": "http://learn.genetics.utah.edu/content/cloning/clickandclone/"},
	{"caption": "Stamceller",
	 "link": "http://learn.genetics.utah.edu/content/stemcells/scintro/"},
	{"caption": "Stamceller og medicin",
	 "link": "http://learn.genetics.utah.edu/content/stemcells/scfuture/"},

	{"color": "#6DC0B4"},

	{"caption": "Learn Genetics",
	 "link": "http://learn.genetics.utah.edu"},
	{"caption": "GMO Compass",
	 "link": "http://www.gmo-compass.org/eng/home/"},
	{"caption": "GMO-sikkerhed",
	 "link": "http://www.gmo-safety.eu"},
	{"caption": "Etisk Råd",
	 "link": "http://www.etiskraad.dk"},
	{"caption": "Videnskab.dk",
	 "link": "http://www.videnskab.dk"},
	{"caption": "Aktuel Naturvidenskab",
	 "link": "http://aktuelnaturvidenskab.dk"}
    ]

}
