var links = [
{'caption':'Bakterier i fødevarer',
'link':'https://www.dropbox.com/s/yizr4amf30dqiev/Bakterier%20i%20f%C3%B8devarer.pdf?dl=0'},
{'caption':'Bakterievækst',
'link':'https://www.dropbox.com/s/zcnaoo1789ua11r/Bakteriev%C3%A6kst.pdf?dl=0'},
{'caption':'Det kommer an på størrelsen',
'link':'https://www.dropbox.com/s/8k3p7wm8clsobgv/Det%20kommer%20an%20p%C3%A5%20st%C3%B8rrelsen.pdf?dl=0'},
{'caption':'Du er ikke alene',
'link':'https://www.dropbox.com/s/zw6pqghxdyd3cxk/Du%20er%20ikke%20alene.pdf?dl=0'},
{'caption':'Laboratoriejournaler',
'link':'https://www.dropbox.com/s/rs3t4samsb5mrra/Laboratoriejournaler%20og%20lego.pdf?dl=0'},
{'caption':'Mikroskopi af plante- og dyreceller',
'link':'https://www.dropbox.com/s/dwkqliylukppj36/Mikroskopi%20af%20plante%20og%20dyreceller.pdf?dl=0'},
{'caption':'Osmose og kartoffelceller',
'link':'https://www.dropbox.com/s/e5agpigdvr6xwyo/Osmose%20og%20kartoffelceller.pdf?dl=0'},
]
