var links = [
{'caption':'Dissektion af svinehjerte',
'link':'https://www.dropbox.com/s/lmn8gqmpe4owb0g/Dissektion%20af%20svinehjerte.pdf?dl=0'},
{'caption':'Måling af hæmatokritværdi',
'link':'https://www.dropbox.com/s/8c4htrd1ztwpfz9/M%C3%A5ling%20af%20h%C3%A6matokritv%C3%A6rdi.pdf?dl=0'},
{'caption':'Puls og arbejde',
'link':'https://www.dropbox.com/s/7ma80bt9y62g5ja/Puls%20og%20arbejde.pdf?dl=0'},
{'caption':'Puls, blodtryk og rygning',
'link':'https://www.dropbox.com/s/pilpau5ziehfs8r/Puls%2C%20blodtryk%20og%20rygning.pdf?dl=0'},
{'caption':'Regulering af åndedræt og blodkredsløb',
'link':'https://www.dropbox.com/s/lq5ymnrj0wurlt4/Regulering%20af%20%C3%A5ndedr%C3%A6t%20og%20blodkredsl%C3%B8b.pdf?dl=0'},
{'caption':'Vener, arterier og kapillærer',
'link':'https://www.dropbox.com/s/n49to35jl3f6n76/Vener%2C%20arterier%20og%20kapill%C3%A6rer.pdf?dl=0'},
{'caption':'Åndedrætssystemet',
'link':'https://www.dropbox.com/s/bcl6w8jl3jgohbc/%C3%85ndedr%C3%A6tssystemet.pdf?dl=0'},
]
