var links = [
{'caption':'En tur til McDonalds',
'link':'https://www.dropbox.com/s/gs1rb85kzajpn5j/En%20tur%20p%C3%A5%20McDonalds.pdf?dl=0'},
{'caption':'Fordøjelse af en burger',
'link':'https://www.dropbox.com/s/6t2mswn07dnvagj/Ford%C3%B8jelse%20af%20en%20burger.pdf?dl=0'},
{'caption':'Fordøjelse af fedtstoffer',
'link':'https://www.dropbox.com/s/xryk9u4g000adgb/Ford%C3%B8jelse%20af%20fedtstoffer.pdf?dl=0'},
{'caption':'Fordøjelse af franskbrød',
'link':'https://www.dropbox.com/s/rt4efnlff4z9ylv/Ford%C3%B8jelse%20af%20franskbr%C3%B8d.pdf?dl=0'},
{'caption':'Fordøjelse',
'link':'https://www.dropbox.com/s/rfrl2hls9r2l0xe/Ford%C3%B8jelse.pdf?dl=0'},
{'caption':'Kostundersøgelse',
'link':'https://www.dropbox.com/s/5no5v88ttkm6j12/Kostunders%C3%B8gelse.pdf?dl=0'},
{'caption':'Kulhydrater og blodsukkeret',
'link':'https://www.dropbox.com/s/pbgu1no0d54v6fr/Kulhydrater%20og%20blodsukkeret.pdf?dl=0'},
{'caption':'Peristaltik',
'link':'https://www.dropbox.com/s/6ewqhp5f06fz4sv/Peristaltik.pdf?dl=0'},
{'caption':'Proteinfordøjelse',
'link':'https://www.dropbox.com/s/0vnfsh4wifqir8y/Proteinford%C3%B8jelse.pdf?dl=0'},
{'caption':'Spytamylase',
'link':'https://www.dropbox.com/s/bpv4dyp2rg9lozl/Spytamylase.pdf?dl=0'},
{'caption':'Sundhedstjek',
'link':'https://www.dropbox.com/s/62cfx25yg5uhzod/Sundhedstjek.pdf?dl=0'},
]
