var tilesData = 
    {"Danmark": ["Peter Schmeichel", 
		 "John Sivebæk",
		 "Kent Nielsen",
		 "Lars Olsen",
		 "Henrik Andersen",
		 "Kim Christofte",
		 "John Faxe Jensen",
		 "Johnny Mølby",
		 "Flemming Povlsen",
		 "Lars Elstrup",
		 "Brian Laudrup",
		 "Torben Piechnik",
		 "Richard Møller Nielsen"],
     
     "England": ["Chris Woods",
		 "Keith Curle",
		 "Stuart Pearce",
		 "Martin Keown",
		 "Des Walker",
		 "Mark Wright",
		 "David Platt",
		 "Trevor Steven",
		 "Nigel Clough",
		 "Gary Lineker",
		 "Andy Sinton",
		 "Carlton Palmer",
		 "Nigel Martyn",
		 "Tony Dorigo",
		 "Neil Webb",
		 "Paul Merson",
		 "Alan Smith",
		 "Tony Daley",
		 "David Batty",
		 "Alan Shearer"],

     "Netherlands": ["Hans van Breukelen",
		     "Berry van Aerle",
		     "Adri van Tiggelen",
		     "Ronald Koeman",
		     "Danny Blind",
		     "Jan Wouters",
		     "Dennis Bergkamp",
		     "Frank Rijkaard",
		     "Marco van Basten",
		     "Ruud Gullit",
		     "John van 't Schip",
		     "Wim Kieft",
		     "Stanley Menzo",
		     "Rob Witschge",
		     "Aron Winter",
		     "Peter Bosz",
		     "Frank de Boer",
		     "Wim Jonk",
		     "Eric Viscaal",
		     "Bryan Roy"],

     "Germany": ["Bodo Illgner",
		 "Stefan Reuter",
		 "Andreas Brehme",
		 "Jürgen Kohler",
		 "Manfred Binz",
		 "Guido Buchwald",
		 "Andreas Möller",
		 "Thomas Häßler",
		 "Rudi Völler",
		 "Thomas Doll",
		 "Karl-Heinz Riedle",
		 "Andreas Köpke",
		 "Andreas Thom",
		 "Thomas Helmer",
		 "Michael Frontzeck",
		 "Matthias Sammer",
		 "Stefan Effenberg",
		 "Jürgen Klinsmann",
		 "Michael Schulz",
		 "Christian Wörns"],

     "Scotland": ["Andy Goram",
		  "Richard Gough",
		  "Paul McStay",
		  "Maurice Malpas",
		  "Ally McCoist",
		  "Brian McClair",
		  "Gordon Durie",
		  "David McPherson",
		  "Stewart McKimmie",
		  "Stuart McCall",
		  "Gary McAllister",
		  "Henry Smith",
		  "Pat Nevin",
		  "Kevin Gallacher",
		  "Tom Boyd",
		  "Jim McInally",
		  "Derek Whyte",
		  "Dave Bowman",
		  "Alan McLaren",
		  "Duncan Ferguson"]
    };
