var links = {
    "7": [
		{"caption": "Befrugtning", "link": "http://www.youtube.com/watch?v=fO4UWj01Gx8"},
		{"caption": "Ægløsning", "link": "http://www.youtube.com/watch?v=nLmg4wSHdxQ"},
		{"caption": "Mandens kønsorganer","link": "https://www.youtube.com/watch?v=-XQcnO4iX_U"},
		{"caption": "Mandens forplantningsorganer", "link": "http://www.youtube.com/watch?v=N66sAZH1VA8"},
		{"caption": "Kvindens kønsorganer","link": "https://www.youtube.com/watch?v=RFDatCchpus"},
		{"caption": "Kvindens forplantningsorganer","link": "http://www.youtube.com/watch?annotation_id=annotation_4029894085&feature=iv&src_vid=N66sAZH1VA8&v=a8fgm-zEYjQ"},
		{"caption": "Befrugtning (og prævention)","link": "https://www.youtube.com/watch?v=SUdAEGXLO-8"},
		{"caption": "Ultralydoptagelser af foster i livmoderen uge for uge","link": "http://www.youtube.com/watch?v=gfgq7WiHbh4"},
		{"caption": "Livet i livmoderen", "link": "http://www.youtube.com/watch?v=RBKKnCtNeRU"},
		{"caption": "Befrugtning samt graviditet uden for livmoderen", "link": "https://www.sundhed.dk/borger/sygdomme-a-aa/graviditet/illustrationer/animationer/graviditet-udenfor-livmoderen/"},
		{"caption": "Fosterudvikling 1", "link": "http://www.hhmi.org/biointeractive/human-embryonic-development"},
		{"caption": "Fosterudvikling 2", "link": "https://www.sundhed.dk/borger/sygdomme-a-aa/graviditet/illustrationer/animationer/fosterudvikling/"},
		{"caption": "Fosterudvikling 3","link": "https://www.youtube.com/watch?v=BtsSbZ85yiQ"},
		{"caption": "Hjernens udvikling","link": "http://www.hhmi.org/biointeractive/development-human-embryonic-brain"},
		{"caption": "Ægløsning, befrugtning, fødsel og kunstig befrugtning", "link": "https://www.sundhed.dk/borger/sygdomme-a-aa/graviditet/illustrationer/animationer/kunstig-befrugtning/"},
		{"caption": "IVF befrugtning","link": "http://www.youtube.com/watch?v=GeigYib39Rs"},
		{"caption": "Impotens 1", "link": "https://www.sundhed.dk/borger/sygdomme-a-aa/maend/illustrationer/animationer/impotens/"},
		{"caption": "Forskellige typer af spiraler","link": "http://www.youtube.com/watch?v=eL1fibjPMKk"},
		{"caption": "Sterilisation af mænd 1", "link": "https://www.sundhed.dk/borger/sygdomme-a-aa/maend/illustrationer/animationer/sterilisering-af-maend-vasektomi/"},
		{"caption": "Om HIV’s livscyklus", "link": "http://www.youtube.com/watch?v=odRyv7V8LAE"},
		{"caption": "Fladlus", "link": "https://www.sundhed.dk/borger/sygdomme-a-aa/hud/illustrationer/animationer/fladlus/"},
		{"caption": "Herpes 2", "link": "https://www.sundhed.dk/borger/sygdomme-a-aa/hud/illustrationer/animationer/herpes/"},
		{"caption":"Kvinders reproduktive system","link":"https://www.youtube.com/watch?v=RFDatCchpus"},
		{"caption":"Mandens reproduktive system","link":"https://www.youtube.com/watch?v=-XQcnO4iX_U"},
		{"caption":"Sex og befrugtning","link":"https://www.youtube.com/watch?v=SUdAEGXLO-8"},
		{"caption":"Graviditet","link":"https://www.youtube.com/watch?v=BtsSbZ85yiQ"},
	{"color": "#6DC0B4"},
	{"caption": "Videnskab.dk", "link": "http://www.videnskab.dk"},
	{"caption": "Aktuel Naturvidenskab","link": "http://aktuelnaturvidenskab.dk"},
	{"caption": "Sciencefix.dk","link": "http://www.sciencefix.dk"},
	{"caption": "Netdoktor.dk","link": "http://www.netdoktor.dk"},
	{"caption": "Sundhed.dk","link": "http://www.sundhed.dk"},
	{"caption": "Motion-online.dk","link": "http://www.motion-online.dk"},
	{"caption": "Statens seruminstituts hjemmeside", "link": "http://www.ssi.dk"},
	{"caption": "Sundhedsstyrelsens hjemmeside", "link": "http://www.sst.dk"},
	{"caption": "Sundhedsguiden.dk", "link": "http://www.sundhedsguiden.dk"},
	{"caption": "Sex og samfund", "link": "https://www.sexogsamfund.dk"},
	{"caption": "Forældre og fødsels hjemmeside", "link": "http://www.fogf.dk"},
	{"caption": "Etisk råd", "link": "http://www.etiskraad.dk"},
	{"caption": "AIDS-fondet", "link": "http://www.aidsfondet.dk"},

	]
}
