var links = {

	"2": [
		{"caption": "Hvordan fungerer lungerne", "link": "https://www.sundhed.dk/borger/sygdomme-a-aa/lunger/illustrationer/animationer/hvordan-fungerer-lungerne/"},
		{"caption": "Lymfesystemet 2","link": "https://www.youtube.com/watch?v=BX8fBlme9vQ"},
		{"caption": "Blodtryk 1","link": "https://www.sundhed.dk/borger/sygdomme-a-aa/hjerte-og-blodkar/illustrationer/animationer/blodtrykket/"},
		{"caption": "Hjertet","link": "https://www.youtube.com/watch?v=rguztY8aqpk&list=PL978360DC8EE52FCB&index=78"},
		{"caption": "Hvordan virker hjerteklapperne","link": "https://www.sundhed.dk/borger/sygdomme-a-aa/hjerte-og-blodkar/illustrationer/animationer/hvordan-virker-hjerteklapperne/"},
		{"caption": "Hvordan virker hjertet","link": "https://www.sundhed.dk/borger/sygdomme-a-aa/hjerte-og-blodkar/illustrationer/animationer/hvordan-arbejder-hjertet/"},
		{"caption": "Blodkar 1","link": "https://www.youtube.com/watch?v=v43ej5lCeBo"},
		{"caption": "Lungernes funktion og lungekræft","link": "https://www.sundhed.dk/borger/sygdomme-a-aa/lunger/illustrationer/animationer/lungekraeft/"},
		{"caption": "Astma","link": "https://www.sundhed.dk/borger/sygdomme-a-aa/lunger/illustrationer/animationer/astma/"},
		{"caption": "Lungebetændelse","link": "https://www.sundhed.dk/borger/sygdomme-a-aa/lunger/illustrationer/animationer/lungebetaendelse/"},
		{"caption": "Blodprop i hjertet 1","link": "https://www.youtube.com/watch?v=n8P3n6GKBSY"},
		{"caption": "Blodprop","link": "http://www.hhmi.org/biointeractive/how-heart-attack-occurs"},
		{"caption": "Åreforkalkning og blodprop","link": "https://www.sundhed.dk/borger/sygdomme-a-aa/hjerte-og-blodkar/illustrationer/animationer/dannelse-af-aareforkalkning-og-blodprop/"},
		{"caption":"Åndedrætssystemet 1","link":"https://www.youtube.com/watch?v=bHZsvBdUC2I"},
		{"caption":"Åndedrætssystemet 2","link":"https://www.youtube.com/watch?v=MrDbiKQOtlU"},
		{"caption":"Gasudveksling 2", "link":"https://www.youtube.com/watch?v=Cqt4LjHnMEA"},
		{"caption":"Blod 1","link":"https://www.youtube.com/watch?v=HQWlcSp9Sls"},
		{"caption":"Blod 2","link":"https://www.youtube.com/watch?v=9-XoM2144tk"},
		{"caption":"Blodkar","link":"https://www.youtube.com/watch?v=v43ej5lCeBo"},
		{"caption":"Blodtryk 2","link":"https://www.youtube.com/watch?v=ZVklPwGALpI"},
		{"caption":"Hjertet 1","link":"https://www.youtube.com/watch?v=X9ZZ6tcxArI"},
		{"caption":"Hjertet 2","link":"https://www.youtube.com/watch?v=FLBMwcvOaEo"},
		{"caption":"Lymfesystemet 1","link":"https://www.youtube.com/watch?v=I7orwMgTQ5I"},
		{"caption":"Blodkredsløbet","link":"https://www.youtube.com/watch?v=NJzJKvkWWDc"},
		,{"color": "#6DC0B4"},
		{"caption": "Videnskab.dk", "link": "http://www.videnskab.dk"},
		{"caption": "Aktuel Naturvidenskab","link": "http://aktuelnaturvidenskab.dk"},
		{"caption": "Sciencefix.dk","link": "http://www.sciencefix.dk"},
		{"caption": "Netdoktor.dk","link": "http://www.netdoktor.dk"},
		{"caption": "Sundhed.dk","link": "http://www.sundhed.dk"},
		{"caption": "Motion-online.dk","link": "http://www.motion-online.dk"},
	   {"caption": "Sundhedsguiden.dk","link": "http://www.sundhedsguiden.dk"},
	 {"caption": "Sundhedsstyrelsen","link": "http://www.sst.dk"},
	 {"caption": "Min Medicin","link": "http://www.min.medicin.dk"},
	 {"caption": "Danmarks Lungeforening","link": "http://www.lunge.dk"},
	 {"caption": "Hjerteforeningen", "link": "https://hjerteforeningen.dk"},
	]}