var links = {
	"1": 
	[
	{"caption": "Bakteriofager", "link": "https://www.youtube.com/watch?v=YI3tsmFsrOg"},
	{"caption": "Forfærdelige parasitter", "link": "https://www.youtube.com/watch?v=qNWWrDBRBqk"},
	{"caption": "Ebola", "link": "https://www.youtube.com/watch?v=sRv19gkZ4E0"},
		{"caption": "Mikrobiomet", "link": "https://www.youtube.com/watch?v=VzPD009qTN4"},
		{"caption": "Celler", "link": "http://www.bozemanscience.com/a-tour-of-the-cell"},
		{"caption": "Antibiotika 2","link": "http://blausen.com/da/video/antibiotika/"},
		{"caption": "Miltbrand","link": "http://blausen.com/da/video/miltbrand/"},
		{"caption": "Pølseforgiftning","link": "https://blausen.com/da/video/pølseforgiftning-botulisme/"},
		{"caption": "Antibiotika 1","link": "https://www.sundhed.dk/borger/sygdomme-a-aa/infektioner/illustrationer/animationer/antibiotika/"},
			{"caption": "Probiotika", "link": "https://www.youtube.com/watch?v=j_5WAJHTPX8"},
			{"caption": "Plasmolyse  ","link": "http://highered.mcgraw-hill.com/sites/9834092339/student_view0/chapter38/animation_-_osmosis.html"},
			{"caption": "Fagocytose","link": "http://highered.mcgraw-hill.com/sites/0072495855/student_view0/chapter2/animation__phagocytosis.html"},
			{"caption": "Diffusion","link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter3/animation__how_diffusion_works.html"},
			{"caption": "Faciliteret diffusion", "link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter3/animation__how_facilitated_diffusion_works.html"},
			{"caption": "Forskellige typer af transport over cellemembranen","link": "http://highered.mcgraw-hill.com/sites/0072437316/student_view0/chapter6/animations.html#"},
			{"caption": "Endosymbiont-teori","link": "http://highered.mcgraw-hill.com/sites/9834092339/student_view0/chapter4/animation_-_endosymbiosis.html"},
			{"caption": "Cellemembranen 2","link": "http://www.youtube.com/watch?v=moPJkCbKjBs"},
			{"caption": "Endocytose og exocytose","link": "http://www.youtube.com/watch?v=K7yku3sa4Y8"},
			{"caption": "Apoptose","link": "http://www.youtube.com/watch?v=6KVQzYO_2tY"},
			{"caption": "Live osmose", "link": "https://www.youtube.com/watch?v=rMtaqq2bmFU"},
			{"caption": "Malaria – mennesket","link": "http://www.hhmi.org/biointeractive/malaria-human-host"},
			{"caption": "Osmose","link": "http://highered.mheducation.com/sites/0072943696/student_view0/chapter3/animation__how_osmosis_works.html"},
			{"caption": "Antiviral medicin","link": "http://blausen.com/da/video/medicin-mod-virus/"},
			{"caption": "HIV-resistens","link": "http://www.youtube.com/watch?v=4zFjh1LrdV4"},
			{"caption": "Influenzavirus","link": "http://www.youtube.com/watch?v=YSgkoldBNkI"},
			{"caption": "Viral rekombination", "link": "http://www.hhmi.org/biointeractive/recombination-viral-genome"},
			{"caption": "Virus’ livscyklus", "link": "http://www.hhmi.org/biointeractive/viral-lifecycle"},
			,{"caption": "Prioner", "link": "http://www.youtube.com/watch?v=pqhpVpafjmk"},
		{"caption":"Planteceller", "link":"https://www.youtube.com/watch?v=9UvlqAVCoqY&index=6&list=PL3EED4C1D684D3ADF"},
		{"caption":"Multiresistente bakterier", "link":"https://www.youtube.com/watch?time_continue=3&v=plVk4NVIUh8"},
		{"caption": "Osmose og diffusion", "link":"https://www.youtube.com/watch?v=LeS2-6zHn6M"},
		{"caption":"Dyr","link":"https://www.youtube.com/watch?v=wd-QnKlfZHI"},
		{"caption":"Planter","link":"https://www.youtube.com/watch?v=X4L3r_XJW0I"},
		{"caption":"Svampe", "link":"https://www.youtube.com/watch?v=dj9m7Oc36wM"},
		{"caption":"Protister","link":"https://www.youtube.com/watch?v=8deF3Rw4ti4"},
		{"caption":"Eukaryoter","link":"https://www.youtube.com/watch?v=bo0QHAS-x8A"},		
		{"caption":"Arkæer","link":"https://www.youtube.com/watch?v=W25nI9kpxtU"},
		{"caption":"Bakterier", "link":"https://www.youtube.com/watch?v=h-z9-9OOWC4"},
		{"caption":"Virus", "link":"https://www.youtube.com/watch?v=L8oHs7G_syI"},
		{"caption":"Cellemembranen 1", "link":"https://www.youtube.com/watch?v=S7CJ7xZOjm0"},
		{"caption":"Organeller","link":"https://www.youtube.com/watch?v=Ot_KmOTYfRA"},
		{"caption":"Størrelsesforhold 1", "link":"https://learn.genetics.utah.edu/content/cells/scale/"},
		{"caption":"Størrelsesforhold 2","link":"https://www.cellsalive.com/howbig_js.htm"},
	
		
		,{"color": "#6DC0B4"},
		
	{"caption": "Videnskab.dk", "link": "http://www.videnskab.dk"},
	{"caption": "Aktuel Naturvidenskab","link": "http://aktuelnaturvidenskab.dk"},
	{"caption": "Sciencefix.dk","link": "http://www.sciencefix.dk"},
	{"caption": "Netdoktor.dk","link": "http://www.netdoktor.dk"},
	{"caption": "Sundhed.dk","link": "http://www.sundhed.dk"},
	{"caption": "Motion-online.dk","link": "http://www.motion-online.dk"},
]
}
