var links = {
    "30": [
	   {"caption": "Eutrofiering","link": "https://www.youtube.com/watch?v=6LAT1gLMPu4"},
	   {"caption": "Drivhuseffekt 1","link": "http://www.hhmi.org/biointeractive/greenhouse-effect"},
	   {"caption": "Drivhuseffekt 2","link": "https://www.youtube.com/watch?v=NPXVKb-k2nU"},
		{"caption":"Forsuring af havet","link":"https://www.youtube.com/watch?v=fgBozLCGUHY"},
		{"caption":"Klimaforandringer 1","link":"https://www.youtube.com/watch?v=QLteLZNXmyI"},
		{"caption":"Klimaforandringer 2","link":"https://www.youtube.com/watch?v=Ou1WFBywN4o"},
		{"caption":"Vandforurening","link":"https://www.youtube.com/watch?v=GNGKsubYJ9U"},
		{"caption":"Luftforurening","link":"https://www.youtube.com/watch?v=_dTtvtlct9k"},
		 	{"caption": "Interaktiv klimaside",	 "link": "https://en-roads.climateinteractive.org/scenario.html?p7=2&p10=0.1&v=2.7.29"},
		,{"color": "#6DC0B4"},
		{"caption": "Videnskab.dk", "link": "http://www.videnskab.dk"},
		{"caption": "Aktuel Naturvidenskab","link": "http://aktuelnaturvidenskab.dk"},
		{"caption": "Sciencefix.dk","link": "http://www.sciencefix.dk"},
		{"caption": "Netdoktor.dk","link": "http://www.netdoktor.dk"},
		{"caption": "Sundhed.dk","link": "http://www.sundhed.dk"},
		{"caption": "Motion-online.dk","link": "http://www.motion-online.dk"},
			{"caption": "Plastik-forurening","link": "https://www.youtube.com/watch?v=RS7IzU2VJIQ"},
	{"caption": "Økologisk Landsforenings hjemmeside", "link": "http://www.okologi.dk/"},

	{"caption": "Hjemmeside med masser af oplysninger om plante- og dyreliv i Danmark",
	 "link": "http://www.naturporten.dk/"},

	{"caption": "Undervisningsmateriale om vand",
	 "link": "http://www.vandetsvej.dk"},
	
	{"caption": "Naturstyrelsens hjemmeside. Links til fredninger mm",
	 "link": "http://www.naturstyrelsen.dk"},
	
	{"caption": "Miljøstyrelsens hjemmeside", "link": "http://www.mst.dk"},
	{"caption": "Danmarks Naturfredningsforenings hjemmeside", "link": "http://www.dn.dk/"},
	{"caption": "Friluftsrådets hjemmeside", "link": "http://www.friluftsraadet.dk/"},
	{"caption": "PCB guiden miljøet", "link": "http://pcb-guiden.dk/"},
	{"caption": "Oplysninger om danske insekter", "link": "http://www.danmarksinsekter.dk/"},
	{"caption": "Oplysninger om fugle i naturen", "link": "http://www.fugleognatur.dk/"},
	{"caption": "Leksikon over fugle med sang!", "link": "http://www.fugleinfo.dk/lex/"},
	{"caption": "Nationalt Center for Miljø og Energi.(Tidligere Danmarks Miljøundersøgelser)", "link": "http://dce.au.dk/"},
	{"caption": "Hjemmeside for de danske vandværker", "link": "http://www.dkvand.dk"},
	{"caption": "Hjemmeside om miljøundersøgelser i Grønland mm.", "link": "http://www.geus.dk"},
	{"caption": "Greenpeaces hjemmeside", "link": "http://www.greenpeace.org/"},
	{"caption": "Danmarks miljøportals hjemmeside. Her kan der findes data om miljø i Danmark",
	 "link": "http://www.miljoeportal.dk/borger/Sider/Borger.aspx"},
	]
}
