var links = [
{'caption':'Det kommer an på størrelsen',
'link':'https://www.dropbox.com/s/rz8ulgneag50o2e/Det%20kommer%20an%20p%C3%A5%20st%C3%B8rrelsen.pdf?dl=0'},
{'caption':'Du er ikke alene',
'link':'https://www.dropbox.com/s/ohgfysp4422nzg7/Du%20er%20ikke%20alene.pdf?dl=0'},
{'caption':'Evolution',
'link':'https://www.dropbox.com/s/jnaf6exf6nb1o1l/Evolution.pdf?dl=0'},
{'caption':'Laboratoriejournaler og lego',
'link':'https://www.dropbox.com/s/ma9zwp9edfthevt/Laboratoriejournaler%20og%20lego.pdf?dl=0'},
{'caption':'Mikroskopi af plante- og dyreceller',
'link':'https://www.dropbox.com/s/6zyozd3nxo76tus/Mikroskopi%20af%20plante%20og%20dyreceller.pdf?dl=0'},
{'caption':'Osmose og kartoffelceller',
'link':'https://www.dropbox.com/s/f4lwojy6ngowql7/Osmose%20og%20kartoffelceller.pdf?dl=0'},
{'caption':'Slægtskab og stamtræer',
'link':'https://www.dropbox.com/s/b9akavyxco74le8/Sl%C3%A6gtskab%20og%20stamtr%C3%A6er.pdf?dl=0'},
{'caption':'Survival of the fittest',
'link':'https://www.dropbox.com/s/giyw5v3exjeodt1/Survival%20of%20the%20fittest.pdf?dl=0'},
{'caption':'Ur-dyret',
'link':'https://www.dropbox.com/s/g8dss11ntmr4cuy/Ur-dyret.pdf?dl=0'},
]
