var links = [
{'caption':'En tur på McDonalds',
'link':'https://www.dropbox.com/s/q5atzvtik9tn4y5/En%20tur%20p%C3%A5%20McDonalds.pdf?dl=0'},
{'caption':'Fordøjelse af en burger',
'link':'https://www.dropbox.com/s/cxyzcnzuxp4fiwn/Ford%C3%B8jelse%20af%20en%20burger.pdf?dl=0'},
{'caption':'Fordøjelse af fedtstoffer',
'link':'https://www.dropbox.com/s/muah7qbsm3zrvrx/Ford%C3%B8jelse%20af%20fedtstoffer.pdf?dl=0'},
{'caption':'Fordøjelse',
'link':'https://www.dropbox.com/s/p9xhwf4eb77w93g/Ford%C3%B8jelse.pdf?dl=0'},
{'caption':'Kostundersøgelse',
'link':'https://www.dropbox.com/s/9o9l76wnmhbc8o7/Kostunders%C3%B8gelse.pdf?dl=0'},
{'caption':'Kulhydrater og blodsukkeret',
'link':'https://www.dropbox.com/s/u3wi7p9ea64lk91/Kulhydrater%20og%20blodsukkeret.pdf?dl=0'},
{'caption':'Spytamylase',
'link':'https://www.dropbox.com/s/ztbzq8rgojs1591/Spytamylase.pdf?dl=0'},
{'caption':'Sundhedstjek',
'link':'https://www.dropbox.com/s/crxpmbzpcaai8mi/Sundhedstjek.pdf?dl=0'},
]
